### ISSUE TITLE
Pre-release extension for testing pre-released core v3

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#318]
The latest VS Code v1.63 has supported pre-release version of the extension. Users can opt in to try a cutting edge version in the VS Code UI.
https://code.visualstudio.com/updates/v1_63#_pre-release-extensions

[Marp ecosystem has shipped our core v3.0.0 as pre-released version](https://github.com/marp-team/marp-core/releases/tag/v3.0.0). This version may be included some breaking changes that require to change to exist slide Markdown and theme CSS. Thus, Marp for VS Code has not taken the latest core and sticks to v2 stable.

Marp CLI already can opt in the pre-released core by manually. However, we might recieve little feedbacks about upcoming changes in core v3 by taking into consideration that many users are beginning Marp from the VS Code extension.

If shipped the pre-released version of Marp extension with containing pre-released core, we could recieve more feedbacks about upcoming changes, and mitigate a risk about breaking user's workflow for creating slide (Just opt-out pre-relase to get back into the stable).

### ToDo

- [x] Think about versioning strategy of VS Code extension (v2 as a pre-release version?)
- [x] Investigate how to use pre-released core in embedded Marp CLI in the extension
- [x] How to treat versioning for the extension published to Open VSX (its marketplace may not support the pre-release extension)

**Comment by yhatt** [comment]
### Versioning

We would no longer make any upcoming releases for Marp for VS Code v1.x. First, the major update v2 including new core will be shipped as a pre-release extension. Early users can opt-in the new version and try the updated rendering result.

Now the latest Marp CLI is bundling a new core so we have no problems just to have using it.

### Open VSX

A pre-release extension support for Open VSX has added by https://github.com/eclipse/openvsx/pull/410. We have already automated publishing to Open VSX, powered by GitHub Actions. Until to reach v2 to stable, we have to publish with a `--pre-release` option.

**Comment by yhatt** [comment]
[v2.0.0](https://github.com/marp-team/marp-vscode/releases/tag/v2.0.0) :+1:

![](https://user-images.githubusercontent.com/3993388/171881511-f0e925a5-5b61-417f-b662-60437d1f0233.png)
