### ISSUE TITLE
Toggle Marp preview by command of quick-picker

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#52]
If there was a command like `markdown.marp.toggleMarpPreview` to toggle `marp` front-matter by command that can access from quick-picker, it would become easy to use.

## ToDo

- [x] Add `markdown.marp.toggleMarpPreview` command
  - [x] Add front-matter section and `marp: true` when front-matter is not detected
  - [x] Replace `marp: true` to `false` when front-matter is detected with `marp: true`
  - [x] Replace `marp: false` to `true` when front-matter is detected with `marp: false`
  - [x] Add `marp: true` to existed section when front-matter is detected without `marp` key
