### ISSUE TITLE
Play slides on VS Code through exported HTML

### ISSUE THREAD

**Issue by yhatt** [marp-team/marp-vscode#87]
Marp for VS Code is just a extension to Markdown pane for preview Marp slides when writing. Normally user should use exported HTML/PDF/PPTX for the practical presentation.

However, We have received some (silent) feedbacks to want to play slideshow on VS Code. We are considering to support playing the exported HTML from Marp CLI directly in VS Code, by adding custom WebView by Marp extension.

A [vscode-reveal extension](https://github.com/evilz/vscode-reveal), based on [reveal.js](https://revealjs.com/), has already supported playing slideshow within VS Code. So we should be able the same with similar approach.

### ToDo

* [ ] Consider a way to export HTML for custom WebView via Marp CLI
  - Generate HTML when executing command? (Presented slides cannot edit dynamically)
  - Use server mode (`--server`)? (Should pay attention to the behavior of [remote extension](https://code.visualstudio.com/api/advanced-topics/remote-extensions))
- [ ] Add custom WebView to render converted HTML
- [ ] Add command to play slideshow

**Comment by apavlenko** [comment]
it would be really great to present slides directly from the VS code!
now I use the preview window for that maximizing it as much as possible...

**Comment by lukebrowell** [comment]
Same here - even if there was a keyboard shortcut for next and previous slide in the preview, and we could full-screen the preview, this would help immensely. I wonder if there is a simpler way to implement this within vscode than how the op is proposing?

**Comment by yhatt** [comment]
The latest VS Code 1.58 is testing an official [Live Preview extension](https://code.visualstudio.com/updates/v1_58#_live-preview) for replacing unmaintained one. By using exported HTML, we can try what if Marp slide can play within VS Code.

![](https://user-images.githubusercontent.com/3993388/125187100-e4523100-e268-11eb-88ef-173fb65550fd.gif)

As pointed out by @lukebrowell, many features are limited in VS Code (e.g. Full screen, presenter view). So we are considering to use [Marp CLI's preview window](https://github.com/marp-team/marp-cli#preview-window---preview---p) as the backend instead of VS Code's WebView. It requires Google Chrome or the flavored browser but there is no restrictions for playing presentation.

**Comment by Jaykul** [comment]
For what it's worth, I prefer the browser option (because of the full-screen option and presenter-mode with notes).

The current experience really just needs:

1. Default to html export instead of pdf
2. Hotkey to re-export without prompting for the file name or overwrite

**Comment by sbibauw** [comment]
I'm unsure why people would need to present from VSCode except for it being a faster work flow (can you confirm, @apavlenko & @lukebrowell?). If that's the case, I think implementing @Jaykul suggestions would make much sense: default to HTML, default of subsequent exports to erase the same file in HTML.
To this, I'd add:
- Add an "**Export and present in HTML**" button or something like it ("Present immediately"?) which would do the same thing as Exporting to HTML + Opening the file (which it already does; though, not sure if it's just me who screwed up the config, but it used to open the HTML in the browser, but now it opens the HTML in VSCode, which isn't really helpful... so make sure that it does something like `open slides.html` rather than `code slides.html`)

Actually, I'd also recommend having multiple options in the Marp menu in VSCode:
- Export to HTML
- Export to PDF
- Export to PPT
rather than the current single Export option with subsequent choice of file type.

**Comment by lukebrowell** [comment]
Confirmed @sbibauw - I use markdown to author slides rapidly for immediate presentation in teams calls and workshops. Workflows which don’t rely on the mouse pointer are optimum.

**Comment by yhatt** [comment]
Nice. Let me organize features:

- **"Start presentation"**: [Opens a new UI-less window for presentation, as just same as Marp CLI's preview window](https://github.com/marp-team/marp-cli#preview-window---preview---p), and then enlarge the slide to fullscreen. _It is following a general workflow on the famous presentation tools like PowerPoint and Keynote._ (So HTML file for presentation would be located in tmp directory)

* Quick export commands
  - It should split into an another issue.

### Remaining

- What a key conbination is better if Marp commands have the default keyboard shortcuts?
- Look into how to control Marp CLI preview window from VS Code
- Support virtual workspace (e.g. Marp document on the remote repository)

**Comment by Wikiwix** [comment]
I would like to present right via VS Code as well.
My idea of the implementation would be basically, the extension running

```bash
marp --preview THE_CURRENT_FILE.md # --preview already implies --watch
```

Ideally with the twist, that not the stored version is watched, but the current working state in the VS Code editor (so it does not require saving changes to disc, to see them in the marp-cli preview window).

**Comment by bilogic** [comment]
is this in progress?

**Comment by mondesirm** [comment]
Just started using Marp and I'm loving it.

> UPDATED: We might not use VS Code WebView in favor of Marp CLI's preview window.

I've been using the `--preview` option but since since this issue is still open, does that mean it was put in the backlog?

If the predicted scope creep is caused by the limitations of VS Code and the need to create a WebView, there are less things to worry about since the release of the new Integrated Browser (in v1.109, January 2026):
- it renders HTML properly unlike its predecessor
- presenter mode works if you "Ctrl+LeftClick" the button: it opens a new tab (I noticed the full screen button is automatically hidden inside VS Code's browser, would it be possible to hide the presenter button as well or BETTER yet, make it so a normal click on the presenter button opens a new tab)

<details><summary>I'll keep using the <code>--preview</code> option but if anyone still wants to play slides inside VS Code, here you go.</summary>
<p>

Took me a few minutes to get a "Start Presentation" task working:

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Marp: Export",
      "type": "shell",
      "command": "pnpm dlx @marp-team/marp-cli \"${file}\" -w", // -w for live changes 
      "problemMatcher": []
    },
    {
      "label": "Marp: Present",
      "type": "shell",
      "dependsOn": ["Marp: Export"],
      "command": "${input:browser}",
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "browser",
      "type": "command",
      "command": "workbench.action.browser.open",
      "args": "file:///C:/marp/example.html" // hard-coded works
      // "args": "file:///${fileDirname}/${fileBasenameNoExtension}.html" // would have been ideal but not working
    }
  ]
}
``` 

Unfortunately, even essential substitutions of variables like `${fileDirname}` isn't supported in inputs... Otherwise, it would have been a perfect temporary solution.

But this issue only arises in tasks and can be easily implemented if the command is provided by the extension.

<details><summary>Optional: Toggle Full Screen replacement</summary>
<p>

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    // ...
    {
      "type": "shell",
      "label": "Hide Title Bar",
      "command": "${command:hideCustomTitleBarInFullScreen}",
      "presentation": { "reveal": "never" },
      "problemMatcher": [],
      "hide": true
    },
    {
      "type": "shell",
      "label": "Toggle Zen Mode",
      "command": "${command:workbench.action.toggleZenMode}",
      "presentation": { "reveal": "never" },
      "problemMatcher": [],
      "hide": true
    }
    // ...
  ],
  // ...
}
```
</p>
</details>

<details><summary>Optional: Pick name and format from VS Code's command palette</summary>
<p>

Some things the default export command does:
1. The OS' native file picker opens (but I always use the same name and folder as the Markdown file)
2. Not every format can be listed in the file picker dropdown (I want to avoid using the CLI and user tasks as much as possible)

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "Marp: Export",
      "command": "pnpm dlx @marp-team/marp-cli \"${file}\" -o \"${input:name}\" -w --${input:format}",
      "presentation": { "reveal": "silent" },
      "problemMatcher": []
    },
    // ...
  ],
  "inputs": [
    {
      "id": "name",
      "type": "promptString",
      "description": "Pick a name (without extension)",
      "default": "slides"
    },
    {
      "id": "format",
      "type": "pickString",
      "description": "Pick a format",
      "default": "pdf",
      "options": [
        "pdf",
        "html",
        "pptx",
        "pptx-editable", // not in the file picker dropdown
        "notes",
        "image png",
        "image jpeg",
        "images png", // missing since the file picker is single file only
        "images jpeg" // missing since the file picker is single file only
      ]
    },
    // ...
  ]
}
```

I might make another issue/PR to address this.
</p>
</details>

</p>
</details>

**Comment by yhatt** [comment]
Yes, I've checked https://code.visualstudio.com/updates/v1_109#_integrated-browser-preview for improved WebView in VS Code.

But currently, Marp for VS Code does not have features to hosting CLI server and remains a simple Markdown preview extension. I'm not sure if we will work on adding such functionality.

Especially it would be difficult to [provide the CLI server for a unsaved Markdown and in-memory file](https://github.com/marp-team/marp-vscode/issues/87#issuecomment-2592352023), the same experience with current Markdown preview.

**Comment by yhatt** [comment]
The experimental setting `markdown.marp.openExportedHtmlInIntegratedBrowser` added in #555 would effectively make satisfy the requirements of this issue by opening the exported HTML in the VS Code built-in browser. It is not possible to reflect unsaved Markdown content, but it may be already sufficient for the actual workflow.

Based on this, we consider better experience, in conjunction with existing issues such as #311.
